name: Build Windows EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          python -m pip install "pyinstaller>=6.4,<7"

      - name: Build EXE
        shell: bash
        run: |
          pyinstaller --onefile --noconsole udp_parser_gui.py
          mkdir -p dist_zip
          powershell -Command "Compress-Archive -Path dist\\udp_parser_gui.exe -DestinationPath dist_zip\\udp_parser_gui.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: udp_parser_gui
          path: dist_zip/udp_parser_gui.zip
          retention-days: 14
